package com.earth.server.common.domain;

public enum ErrorCode {
  DUPLICATE_NICKNAME,
  ACCESS_DENY,
  UNAUTHORIZED,
  EXPIRE_TOKEN,
  INVALID_TOKEN,
  UNEXPECTED_SERVER_ERROR,
  INVALID_REQUEST,
  INVALID_NICKNAME,
  INVALID_PASSWORD,
  NOT_EXIST_USER,
  NOT_MATCH_PASSWORD,
}
